/* Configure these values for the target Supabase project. */
const SUPABASE_URL = window.CURTO_SUPABASE_URL || 'https://emzpvmctqthledjczjah.supabase.co';
const SUPABASE_ANON_KEY = window.CURTO_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtenB2bWN0cXRobGVkamN6amFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg4MDg1ODcsImV4cCI6MjEwNDM4NDU4N30.4d_6n9L_OdaPkkJDg4rsSeIJOx1d4h5Qch8LGD-ld8o';
const db = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
const $ = (id) => document.getElementById(id);
let currentSection = 'overview';
const definitions = { produtos:{label:'Produtos',table:'produtos',columns:[['codigo_sku','SKU'],['nome_pt','Nome'],['unidade_medida','Unidade'],['preco_venda','Preço venda']],fields:[['codigo_sku','SKU'],['nome_pt','Nome'],['unidade_medida','Unidade (UN/KG/PCT/L)'],['preco_custo','Preço de custo','number'],['preco_venda','Preço de venda','number'],['estoque_minimo_seguranca','Estoque mínimo','number']]},categorias:{label:'Categorias',table:'categorias',columns:[['nome_pt','Nome'],['slug','Slug'],['ativo','Ativa']],fields:[['nome_pt','Nome'],['slug','Slug']]},fornecedores:{label:'Fornecedores',table:'fornecedores',columns:[['razao_social','Razão social'],['nome_fantasia','Nome fantasia'],['pais','País'],['moeda_padrao','Moeda']],fields:[['razao_social','Razão social'],['nome_fantasia','Nome fantasia'],['pais','País (BR/PY)'],['moeda_padrao','Moeda (BRL/PYG/USD)'],['telefone_whatsapp','WhatsApp']]},unidades:{label:'Unidades',table:'unidades',columns:[['nome','Nome'],['pais','País'],['moeda','Moeda'],['ativo','Ativa']],fields:[['nome','Nome'],['pais','País (BR/PY)'],['moeda','Moeda (BRL/PYG/USD)']]}};
async function requireManager(){const {data:{session}}=await db.auth.getSession();if(!session)return showLogin();const {data:user,error}=await db.from('usuarios').select('nome,email,perfil_acesso').eq('auth_user_id',session.user.id).eq('ativo',true).maybeSingle();if(error||!user||user.perfil_acesso!=='GESTOR'){await db.auth.signOut();return showLogin('Acesso permitido somente para usuários GESTOR.')} $('user-email').textContent=user.nome||session.user.email;showApp()}
function showLogin(error=''){ $('login-view').classList.remove('hidden');$('app-view').classList.add('hidden');$('login-error').textContent=error }
function showApp(){ $('login-view').classList.add('hidden');$('app-view').classList.remove('hidden');render() }
async function render(){const title=currentSection==='overview'?'Visão geral':definitions[currentSection].label;$('page-title').textContent=title;if(currentSection==='overview')return $('page-content').innerHTML='<div class="cards"><div class="card"><p>Produtos cadastrados</p><strong id="count-products">—</strong></div><div class="card"><p>Fornecedores</p><strong id="count-suppliers">—</strong></div><div class="card"><p>Unidades ativas</p><strong id="count-units">—</strong></div></div><div class="crud"><h3>Seu ambiente está protegido</h3><p class="muted">Todas as telas administrativas exigem sessão válida e perfil GESTOR.</p></div>',loadCounts();const d=definitions[currentSection];$('page-content').innerHTML='<div class="crud"><div class="crud-head"><h3>'+d.label+'</h3><button class="primary" id="new-record">+ Novo registro</button></div><div class="table-wrap"><table><thead><tr>'+d.columns.map(c=>'<th>'+c[1]+'</th>').join('')+'<th>Ações</th></tr></thead><tbody id="rows"><tr><td colspan="'+(d.columns.length+1)+'">Carregando…</td></tr></tbody></table></div></div>'; $('new-record').onclick=()=>openForm(d);loadRows(d)}
async function loadCounts(){for(const [key,d] of Object.entries(definitions)){const {count}=await db.from(d.table).select('*',{count:'exact',head:true});const el=$('count-'+(key==='produtos'?'products':key==='fornecedores'?'suppliers':'units'));if(el)el.textContent=count??0}}
async function loadRows(d){const {data,error}=await db.from(d.table).select('*').order('criado_em',{ascending:false});const rows=$('rows');if(error)return rows.innerHTML='<tr><td colspan="9" class="empty">Não foi possível carregar. Verifique as políticas RLS.</td></tr>';rows.innerHTML=data?.length?data.map(row=>'<tr>'+d.columns.map(c=>'<td>'+String(row[c[0]]??'—')+'</td>').join('')+'<td><button class="action edit">Editar</button><button class="action danger delete">Excluir</button></td></tr>').join(''):'<tr><td colspan="9" class="empty">Nenhum registro encontrado.</td></tr>';[...rows.querySelectorAll('tr')].forEach((tr,i)=>{tr.querySelector('.edit')?.addEventListener('click',()=>openForm(d,data[i]));tr.querySelector('.delete')?.addEventListener('click',()=>removeRow(d,data[i]))})}
function openForm(d,row={}){const values=d.fields.map(f=>'<label>'+f[1]+'<input name="'+f[0]+'" type="'+(f[2]||'text')+'" value="'+(row[f[0]]??'')+'" required /></label>').join('');$('page-content').insertAdjacentHTML('afterbegin','<div class="crud" id="form-box"><form id="record-form"><div class="crud-head"><h3>'+ (row.id?'Editar':'Novo')+' · '+d.label+'</h3><button type="button" class="action" id="cancel">Cancelar</button></div>'+values+'<button class="primary" type="submit">Salvar registro</button></form></div>');$('cancel').onclick=()=>document.getElementById('form-box').remove();$('record-form').onsubmit=async(e)=>{e.preventDefault();const payload=Object.fromEntries(new FormData(e.target));d.fields.forEach(f=>{if(f[2]==='number')payload[f[0]]=Number(payload[f[0]])});const q=row.id?db.from(d.table).update(payload).eq('id',row.id):db.from(d.table).insert(payload);const {error}=await q;if(error)return toast(error.message,true);toast('Registro salvo com sucesso.');document.getElementById('form-box').remove();loadRows(d)}}
async function removeRow(d,row){if(!confirm('Excluir este registro?'))return;const {error}=await db.from(d.table).delete().eq('id',row.id);if(error)return toast(error.message,true);toast('Registro excluído.');loadRows(d)}function toast(message,bad=false){$('toast').textContent=message;$('toast').style.color=bad?'#a33b31':'#26705e'}
$('login-form').onsubmit=async(e)=>{e.preventDefault();$('login-error').textContent='';const {error}=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)return showLogin(error.message);requireManager()};$('logout').onclick=async()=>{await db.auth.signOut();showLogin()};document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{currentSection=b.dataset.section;document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===b));render()});db.auth.onAuthStateChange((_event,session)=>{if(session)requireManager();else showLogin()});requireManager();
